package org.fiteagle.interactors.sfa.common;

public enum SFAv3MethodsEnum {
	GET_VERSION,LIST_RESOURCES, DESCRIBE, ALLOCATE, RENEW, PROVISION, STATUS, PERFORM_OPERATIONAL_ACTION, DELETE, SHUTDOWN, GET_SELF_CREDENTIAL;
}
