//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.28 at 02:10:13 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.geni.net/resources/rspec/3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.fiteagle.interactors.sfa.rspec;
