//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.20 at 04:24:42 PM CEST 
//


package org.fiteagle.interactors.sfa.rspec.ext.openstack;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for flavor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="flavor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ram" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OS-FLV-DISABLED" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="vcpus" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="os-flavor-accessIs_public" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="swap" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="disk" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OS-FLV-EXT-DATAEphemeral" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rxtx_factor" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flavor")
public class Flavor {

    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "ram")
    protected String ram;
    @XmlAttribute(name = "OS-FLV-DISABLED")
    protected Boolean osflvdisabled;
    @XmlAttribute(name = "vcpus")
    protected String vcpus;
    @XmlAttribute(name = "os-flavor-accessIs_public")
    protected Boolean osFlavorAccessIsPublic;
    @XmlAttribute(name = "swap")
    protected String swap;
    @XmlAttribute(name = "disk")
    protected String disk;
    @XmlAttribute(name = "OS-FLV-EXT-DATAEphemeral")
    protected Integer osflvextdataEphemeral;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "rxtx_factor")
    protected Float rxtxFactor;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the ram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRam() {
        return ram;
    }

    /**
     * Sets the value of the ram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRam(String value) {
        this.ram = value;
    }

    /**
     * Gets the value of the osflvdisabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOSFLVDISABLED() {
        return osflvdisabled;
    }

    /**
     * Sets the value of the osflvdisabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOSFLVDISABLED(Boolean value) {
        this.osflvdisabled = value;
    }

    /**
     * Gets the value of the vcpus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVcpus() {
        return vcpus;
    }

    /**
     * Sets the value of the vcpus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVcpus(String value) {
        this.vcpus = value;
    }

    /**
     * Gets the value of the osFlavorAccessIsPublic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOsFlavorAccessIsPublic() {
        return osFlavorAccessIsPublic;
    }

    /**
     * Sets the value of the osFlavorAccessIsPublic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOsFlavorAccessIsPublic(Boolean value) {
        this.osFlavorAccessIsPublic = value;
    }

    /**
     * Gets the value of the swap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwap() {
        return swap;
    }

    /**
     * Sets the value of the swap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwap(String value) {
        this.swap = value;
    }

    /**
     * Gets the value of the disk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisk() {
        return disk;
    }

    /**
     * Sets the value of the disk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisk(String value) {
        this.disk = value;
    }

    /**
     * Gets the value of the osflvextdataEphemeral property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOSFLVEXTDATAEphemeral() {
        return osflvextdataEphemeral;
    }

    /**
     * Sets the value of the osflvextdataEphemeral property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOSFLVEXTDATAEphemeral(Integer value) {
        this.osflvextdataEphemeral = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the rxtxFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getRxtxFactor() {
        return rxtxFactor;
    }

    /**
     * Sets the value of the rxtxFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRxtxFactor(Float value) {
        this.rxtxFactor = value;
    }

}
