//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.20 at 04:24:42 PM CEST 
//


package org.fiteagle.interactors.sfa.rspec.ext.openstack;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.fiteagle.interactors.sfa.rspec.ext.openstack package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Vm_QNAME = new QName("http://fiteagle.org/rspec/ext/1/openstackVMResource", "vm");
    private final static QName _VmToInstantiate_QNAME = new QName("http://fiteagle.org/rspec/ext/1/openstackVMResource", "vmToInstantiate");
    private final static QName _OpenstackResource_QNAME = new QName("http://fiteagle.org/rspec/ext/1/openstackVMResource", "openstackResource");
    private final static QName _Flavors_QNAME = new QName("http://fiteagle.org/rspec/ext/1/openstackVMResource", "flavors");
    private final static QName _Image_QNAME = new QName("http://fiteagle.org/rspec/ext/1/openstackVMResource", "image");
    private final static QName _Flavor_QNAME = new QName("http://fiteagle.org/rspec/ext/1/openstackVMResource", "flavor");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.fiteagle.interactors.sfa.rspec.ext.openstack
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VmToInstantiate }
     * 
     */
    public VmToInstantiate createVmToInstantiate() {
        return new VmToInstantiate();
    }

    /**
     * Create an instance of {@link Vm }
     * 
     */
    public Vm createVm() {
        return new Vm();
    }

    /**
     * Create an instance of {@link Flavor }
     * 
     */
    public Flavor createFlavor() {
        return new Flavor();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Flavors }
     * 
     */
    public Flavors createFlavors() {
        return new Flavors();
    }

    /**
     * Create an instance of {@link OpenstackResource }
     * 
     */
    public OpenstackResource createOpenstackResource() {
        return new OpenstackResource();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Vm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fiteagle.org/rspec/ext/1/openstackVMResource", name = "vm")
    public JAXBElement<Vm> createVm(Vm value) {
        return new JAXBElement<Vm>(_Vm_QNAME, Vm.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VmToInstantiate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fiteagle.org/rspec/ext/1/openstackVMResource", name = "vmToInstantiate")
    public JAXBElement<VmToInstantiate> createVmToInstantiate(VmToInstantiate value) {
        return new JAXBElement<VmToInstantiate>(_VmToInstantiate_QNAME, VmToInstantiate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenstackResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fiteagle.org/rspec/ext/1/openstackVMResource", name = "openstackResource")
    public JAXBElement<OpenstackResource> createOpenstackResource(OpenstackResource value) {
        return new JAXBElement<OpenstackResource>(_OpenstackResource_QNAME, OpenstackResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flavors }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fiteagle.org/rspec/ext/1/openstackVMResource", name = "flavors")
    public JAXBElement<Flavors> createFlavors(Flavors value) {
        return new JAXBElement<Flavors>(_Flavors_QNAME, Flavors.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Image }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fiteagle.org/rspec/ext/1/openstackVMResource", name = "image")
    public JAXBElement<Image> createImage(Image value) {
        return new JAXBElement<Image>(_Image_QNAME, Image.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flavor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fiteagle.org/rspec/ext/1/openstackVMResource", name = "flavor")
    public JAXBElement<Flavor> createFlavor(Flavor value) {
        return new JAXBElement<Flavor>(_Flavor_QNAME, Flavor.class, null, value);
    }

}
