//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.20 at 04:24:42 PM CEST 
//


package org.fiteagle.interactors.sfa.rspec.ext.openstack;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for openstackResource complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="openstackResource">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://fiteagle.org/rspec/ext/1/openstackVMResource}flavors"/>
 *         &lt;element ref="{http://fiteagle.org/rspec/ext/1/openstackVMResource}image"/>
 *         &lt;element ref="{http://fiteagle.org/rspec/ext/1/openstackVMResource}vm"/>
 *         &lt;element ref="{http://fiteagle.org/rspec/ext/1/openstackVMResource}vmToInstantiate"/>
 *       &lt;/sequence>
 *       &lt;attribute name="resourceId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "openstackResource", propOrder = {
    "flavors",
    "image",
    "vm",
    "vmToInstantiate"
})
public class OpenstackResource {

    @XmlElement(required = true)
    protected Flavors flavors;
    @XmlElement(required = true)
    protected Image image;
    @XmlElement(required = true)
    protected Vm vm;
    @XmlElement(required = true)
    protected VmToInstantiate vmToInstantiate;
    @XmlAttribute(name = "resourceId")
    protected String resourceId;

    /**
     * Gets the value of the flavors property.
     * 
     * @return
     *     possible object is
     *     {@link Flavors }
     *     
     */
    public Flavors getFlavors() {
        return flavors;
    }

    /**
     * Sets the value of the flavors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flavors }
     *     
     */
    public void setFlavors(Flavors value) {
        this.flavors = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link Image }
     *     
     */
    public Image getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link Image }
     *     
     */
    public void setImage(Image value) {
        this.image = value;
    }

    /**
     * Gets the value of the vm property.
     * 
     * @return
     *     possible object is
     *     {@link Vm }
     *     
     */
    public Vm getVm() {
        return vm;
    }

    /**
     * Sets the value of the vm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vm }
     *     
     */
    public void setVm(Vm value) {
        this.vm = value;
    }

    /**
     * Gets the value of the vmToInstantiate property.
     * 
     * @return
     *     possible object is
     *     {@link VmToInstantiate }
     *     
     */
    public VmToInstantiate getVmToInstantiate() {
        return vmToInstantiate;
    }

    /**
     * Sets the value of the vmToInstantiate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VmToInstantiate }
     *     
     */
    public void setVmToInstantiate(VmToInstantiate value) {
        this.vmToInstantiate = value;
    }

    /**
     * Gets the value of the resourceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * Sets the value of the resourceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceId(String value) {
        this.resourceId = value;
    }

}
