//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.20 at 04:24:42 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://fiteagle.org/rspec/ext/1/openstackVMResource", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.fiteagle.interactors.sfa.rspec.ext.openstack;
