//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.20 at 04:24:42 PM CEST 
//


package org.fiteagle.interactors.sfa.rspec.ext.openstack;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for vm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="updated" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="hostId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="key_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OS-EXT-STS_Task_state" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OS-EXT-STS_Vm_state" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OS-EXT-AZ_Availability_zone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="user_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="created" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="tenant_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OS-DCF_DiskConfig" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="accessIPv4" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="accessIPv6" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OS-EXT-STS_Power_state" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="config_drive" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="progress" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="imageId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="flavorId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vm")
public class Vm {

    @XmlAttribute(name = "status")
    protected String status;
    @XmlAttribute(name = "updated")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updated;
    @XmlAttribute(name = "hostId")
    protected String hostId;
    @XmlAttribute(name = "key_name")
    protected String keyName;
    @XmlAttribute(name = "OS-EXT-STS_Task_state")
    protected String osextstsTaskState;
    @XmlAttribute(name = "OS-EXT-STS_Vm_state")
    protected String osextstsVmState;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "OS-EXT-AZ_Availability_zone")
    protected String osextazAvailabilityZone;
    @XmlAttribute(name = "user_id")
    protected String userId;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "created")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar created;
    @XmlAttribute(name = "tenant_id")
    protected String tenantId;
    @XmlAttribute(name = "OS-DCF_DiskConfig")
    protected String osdcfDiskConfig;
    @XmlAttribute(name = "accessIPv4")
    protected String accessIPv4;
    @XmlAttribute(name = "accessIPv6")
    protected String accessIPv6;
    @XmlAttribute(name = "OS-EXT-STS_Power_state")
    protected String osextstsPowerState;
    @XmlAttribute(name = "config_drive")
    protected String configDrive;
    @XmlAttribute(name = "progress")
    protected Integer progress;
    @XmlAttribute(name = "imageId")
    protected String imageId;
    @XmlAttribute(name = "flavorId")
    protected String flavorId;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the updated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdated() {
        return updated;
    }

    /**
     * Sets the value of the updated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdated(XMLGregorianCalendar value) {
        this.updated = value;
    }

    /**
     * Gets the value of the hostId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostId() {
        return hostId;
    }

    /**
     * Sets the value of the hostId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostId(String value) {
        this.hostId = value;
    }

    /**
     * Gets the value of the keyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * Sets the value of the keyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyName(String value) {
        this.keyName = value;
    }

    /**
     * Gets the value of the osextstsTaskState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSEXTSTSTaskState() {
        return osextstsTaskState;
    }

    /**
     * Sets the value of the osextstsTaskState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSEXTSTSTaskState(String value) {
        this.osextstsTaskState = value;
    }

    /**
     * Gets the value of the osextstsVmState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSEXTSTSVmState() {
        return osextstsVmState;
    }

    /**
     * Sets the value of the osextstsVmState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSEXTSTSVmState(String value) {
        this.osextstsVmState = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the osextazAvailabilityZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSEXTAZAvailabilityZone() {
        return osextazAvailabilityZone;
    }

    /**
     * Sets the value of the osextazAvailabilityZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSEXTAZAvailabilityZone(String value) {
        this.osextazAvailabilityZone = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the created property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreated(XMLGregorianCalendar value) {
        this.created = value;
    }

    /**
     * Gets the value of the tenantId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * Sets the value of the tenantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenantId(String value) {
        this.tenantId = value;
    }

    /**
     * Gets the value of the osdcfDiskConfig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSDCFDiskConfig() {
        return osdcfDiskConfig;
    }

    /**
     * Sets the value of the osdcfDiskConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSDCFDiskConfig(String value) {
        this.osdcfDiskConfig = value;
    }

    /**
     * Gets the value of the accessIPv4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessIPv4() {
        return accessIPv4;
    }

    /**
     * Sets the value of the accessIPv4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessIPv4(String value) {
        this.accessIPv4 = value;
    }

    /**
     * Gets the value of the accessIPv6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessIPv6() {
        return accessIPv6;
    }

    /**
     * Sets the value of the accessIPv6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessIPv6(String value) {
        this.accessIPv6 = value;
    }

    /**
     * Gets the value of the osextstsPowerState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSEXTSTSPowerState() {
        return osextstsPowerState;
    }

    /**
     * Sets the value of the osextstsPowerState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSEXTSTSPowerState(String value) {
        this.osextstsPowerState = value;
    }

    /**
     * Gets the value of the configDrive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigDrive() {
        return configDrive;
    }

    /**
     * Sets the value of the configDrive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigDrive(String value) {
        this.configDrive = value;
    }

    /**
     * Gets the value of the progress property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProgress() {
        return progress;
    }

    /**
     * Sets the value of the progress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProgress(Integer value) {
        this.progress = value;
    }

    /**
     * Gets the value of the imageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * Sets the value of the imageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageId(String value) {
        this.imageId = value;
    }

    /**
     * Gets the value of the flavorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlavorId() {
        return flavorId;
    }

    /**
     * Sets the value of the flavorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlavorId(String value) {
        this.flavorId = value;
    }

}
